import Footer from "./components/footer/Footer";
import NavBar from "./components/menu/header/NavBar";
import SearchMenu from "./components/menu/searchMenu/SearchMenu";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar-wrapper sticky top-0 bg-white z-50">
          <NavBar />
        </div>
        <SearchMenu />
        <main className="bg-gray-700 py-5">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
